# SwiftLint Configuration for GranaStreamApp
# Configuração focada em manter qualidade do código e identificar debt técnico

# Regras desabilitadas
disabled_rules:
  - trailing_whitespace
  - identifier_name
  - nesting

# Regras opt-in habilitadas
opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_string
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - yoda_condition

# Configuração de regras
line_length:
  warning: 150
  error: 500
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

file_length:
  warning: 400
  error: 600
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

large_tuple:
  warning: 3
  error: 4

# Pastas a serem analisadas
included:
  - GranaStreamApp

# Pastas excluídas da análise
excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData
  - "*.generated.swift"

# Configurações adicionais
reporter: "xcode"
